Write-Host "Hello"
Write-Host "......"
Write-Host "If I was a threat actor with malicious intent"
Write-Host "I would say something on the lines of:"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Thanks for letting me into your system"
Write-Host "I now have access to everything"
Write-Host "And now"
Write-Host "......"
Write-Host "I do mean... EVERYTHING"
Write-Host "......"
Write-Host "Thanks"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Please be CAREFUL with what files you open and USBs you do NOT know"
Write-Host "Take care"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Oh and here's a smiley face:"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "     ========                ========      "
Write-Host "    =        =              =        =     "
Write-Host "   ||        ||            ||        ||    "
Write-Host "    =        =              =        =     "
Write-Host "     ========                ========      "
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "       |==                     ==|         "
Write-Host "        ===                   ===          "
Write-Host "          ======          ======           "
Write-Host "               ============                "
Read-Host